#!/bin/sh

rm -rf $HOME/.config/hosts.nix
touch $HOME/.config/hosts.nix

sudo docker run --pull always --rm -it -v $HOME/.config/hosts.nix:/etc/hosts ghcr.io/stevenblack/hosts:latest updateHostsFile.py --auto --replace --extensions gambling porn

sed -i -e '1i\
\
# START OF CUSTOM BLACKLIST\
\
#0.0.0.0 tiktok.com\
#0.0.0.0 www.tiktok.com\
#0.0.0.0 www.instagram.com\
\
# END OF CUSTOM BLACKLIST\
\
' $HOME/.config/hosts.nix

sed -i "1s/^/{\nnetworking.extraHosts = '' \n/" $HOME/.config/hosts.nix
echo "'';}" >> $HOME.config/hosts.nix

sed -i -e '1i\
# DO NOT EDIT THIS FILE, EDIT THE SCRIPT THAT CREATES THIS FILE IN $HOME/.scripts/hosts.sh\n' $HOME/.config/hosts.nix

sudo nixos-rebuild switch
